### ISSUE TITLE
Too much tall shape around the menu button

### ISSUE THREAD

**Issue by rene-coty** [toolstack/Folio#10]
Just noticed the shape around the menu button is a bit too tall, it should keep a normal margin on top and below 😉

Screenshot : 
 
![Capture d’écran du 2024-03-04 16-53-17](https://github.com/toolstack/Folio/assets/95506494/09804b7f-0033-41dc-94ae-0a438d2b349a)

**Comment by toolstack** [comment]
Yep, though in three pane layout it's fine 🤷
