### ISSUE TITLE
Allow to create single ASCII files (.txt)

### ISSUE THREAD

**Issue by PHHENS** [toolstack/Folio#102]
It could be nice to allow creating single ASCII when adding a new file.

**Comment by toolstack** [comment]
Just right click the note in Folio and select rename, then rename it to .txt right there.  No need to go to a file browser and restart.

**Comment by PHHENS** [comment]
It works ! Thanks for the tip.
I thought it does not accept file extensions when renaming.
Thanks

**Comment by toolstack** [comment]
Np, I only found the feature myself a couple of week ago when I was going through some of the code :smile:
