### ISSUE TITLE
Allow opening files with appropriate external applications

### ISSUE THREAD

**Issue by PHHENS** [toolstack/Folio#106]
Dear Greg,

The kick browsing through miller's columns is a key feature of folio.
The files which are not MD type are recognized (TXT, PDF, XLS...), and TXT file can
be edited. It would be nice to allow other files types (PDF, XLS...)  been opened 
with appropriate external app (eg : evince for PDF ...).

Thanks for understanding this need

**Comment by toolstack** [comment]
That's definitely a problem, only md and text files should be visible in Folio, otherwise you might do something bad and overwrite other files types with text.

My first thought here is to exclude these other file types from the UI, but perhaps an "Open externally" button might make sense too.

**Comment by PHHENS** [comment]
I think Folio should open internally TXT and MD, and by default open externally all other files types (PDF, ODS ...) ?
