### ISSUE TITLE
open link doesn´t work

### ISSUE THREAD

**Issue by rie39414** [toolstack/Folio#110]
there is no hotkey to open link in folio 24.10 for ubuntu 44.04

when i use CTRL+left click, appears (as in the submitted screenshoot):

"couldn't find an app to handle file urls"
![Schermata del 2024-05-05 17-06-34](https://github.com/toolstack/Folio/assets/145783398/a4388c66-43c3-4702-b726-28a5526e2cf0)

i don´t know if it is an error, but i would like to have this feature

[thx for the work btw, i am trying folio in these days with sync between laptop and desktop by filen.io]

**Comment by toolstack** [comment]
That sounds like there isn't a registered handler for web links in Ubuntu.

Which package for Folio are you using, snap or flatpak?

**Comment by rie39414** [comment]
i am using flatpak, i installed now the snap version (24.10) and links work perfectly!

**Comment by toolstack** [comment]
Probably something broken with Ubuntu in their war on flatpaks 🤷😉

I'll install a test Ubuntu and see if it's something fixable in the flatpak or not, I suspect not.

**Comment by toolstack** [comment]
I couldn't replicate the issue on a clean install of Ubuntu 24.04, so I'm closing for now, if I get more reports I'll take a second look at it.
