### ISSUE TITLE
Deleting notebooks is not possible and the attempt creates a "~" folder in the home directory

### ISSUE THREAD

**Issue by heldderarbeit** [toolstack/Folio#112]
Starting from a clean install:

1. Create a new notebook
2. Right click on it and try to "Move all to trash" -> Delete Notebook
3. it was not successful and the output is 

```
(com.toolstack.Folio:2): GLib-GIO-CRITICAL **: 21:32:40.557: GFileInfo created without standard::display-name

(com.toolstack.Folio:2): GLib-GIO-CRITICAL **: 21:32:40.557: file ../gio/gfileinfo.c: line 1721 (g_file_info_get_display_name): should not be reached


** (com.toolstack.Folio:2): CRITICAL **: 21:32:40.557: string_to_string: assertion 'self != NULL' failed
```

![image](https://github.com/toolstack/Folio/assets/4840355/d268891f-34cc-4a7f-9b2f-b6e4ff9de731)

5. Notice how you now have an additional ~ folder **inside** your home directory, so basically ~ nested inside ~.

The deleted notebook appears in 

`~/~/.var/app/com.toolstack.Folio/data/.trash/TestNB`

instead of 

`~/.var/app/com.toolstack.Folio/data/.trash/TestNB`, so I assume that's where things go wrong.

Installed version is 24.10 from Flathub

**Comment by heldderarbeit** [comment]
Btw this bug was introduced with the version:

```
Commit: ada8f37b73021ae00e8e5c596daffb9594f61f7354beab4b0adfd6f420359634
Subject: Release 24.07. (ae65b7b8)
Date: 2024-03-18 18:31:30 +0000
```

With the previous version

```
Commit: 46eb753843ef50f9ebb4f52527bc01329a26de4bc83c32f7e485fa65388b6468
Subject: Update for 24.06 release. (450e0022)
Date: 2024-03-12 22:35:45 +0000
```
everthing is still working as expected.

**Comment by toolstack** [comment]
Can confirm, will investigate and resolve.

**Comment by heldderarbeit** [comment]
Hello, seems like this behaviour is still/again present on Folio 24.11 from Flathub.

The steps to reproduce are still the same:

Right click on notebook - Move all to trash - Delete Notebook

"Could not delete Notebook" toast appears

`/home/username/~/.var/app/com.toolstack.Folio/data/.trash is created`

so again nested "~"

Console output is only 

```
** (process:74612): WARNING **: 02:07:49.799: Error writing credentials to socket: Error sending message: Broken pipe

(com.toolstack.Folio:2): Gtk-WARNING **: 02:07:57.466: GtkBox 0x630171b50ef0 (box) reported min width -3, but sizes must be >= 0
```

**Comment by toolstack** [comment]
Will double check and see what's going on.

**Comment by toolstack** [comment]
@heldderarbeit I've looked into this and I don't think it is the same issue, can you check to see if a directory in your trash already exists for the notebook you're trying to delete?

If so, remove it and try deleting the notebook again.

**Comment by heldderarbeit** [comment]
> in your trash

With 'trash' you mean this screen?

![Screenshot From 2024-10-04 00-30-33](https://github.com/user-attachments/assets/409a2dd4-90c6-4e1c-a0a2-b8021cdf70a1)

I don't think it can already exist there since I'm not able to move notebooks into the trash.

Edit: You don't need to delete a notebook to trigger the creation of the `~/~` folder. Just **clicking** on the trash icon is enough to create the `~/~` folder, you don't need to create a notebook to trigger this bug

1) remove all Folio traces  (`~/.var/app/com.toolstack.Folio` and `~/~`) and start the app from a clean slate
2) click on the trash icon
3) notice how the folder `~/~` is created


[Screencast From 2024-10-04 00-46-08.webm](https://github.com/user-attachments/assets/b89e6298-63ea-4244-b1a5-77acf4314af0)

**Comment by toolstack** [comment]
Ok, it looks like this is fixed in the development branch, so next release should resolve it.

I'll leave this open for the time being until after the next release to verify it works for you.

**Comment by toolstack** [comment]
Closing as 24.12 is released and (cross fingers) resolves this issue.

**Comment by heldderarbeit** [comment]
So sorry to say I can still trigger it in the latest version Folio 24.12.

[Screencast From 2024-10-23 23-28-06.webm](https://github.com/user-attachments/assets/82e3424f-2fcd-4f99-9cec-f87fe5e7705f)

**Comment by toolstack** [comment]
I'll take another look, I was able to recreate the creation of the ~ directory in home, but not the delete failure.
