### ISSUE TITLE
Feature Request : Allow custom stylesheets.

### ISSUE THREAD

**Issue by eriolloan** [toolstack/Folio#117]
I'd like to fix some typography problems (mostly scale and spacing).

Looking around I can't find a stylesheet (CSS or otherwise) to modify.
Is there a way for users to modify the editor appearance ?

Thanks for keeping this project alive.

**Comment by toolstack** [comment]
There is no stylesheet per say (there is one for the main app), but there are styles that are defined for the various markdown items in the sourceview control.

The note font is controlled in the [edit_view code](https://github.com/toolstack/Folio/blob/d5ff13ec72d8ca053c933a8202c89b0750cd3496/src/ui/edit_view/edit_view.vala#L403) while the styles are defined in the [markdown_view widget](https://github.com/toolstack/Folio/blob/d5ff13ec72d8ca053c933a8202c89b0750cd3496/src/ui/widgets/markdown/markdown_view.vala#L540).

There's no easy way for a "user" to alter the appearance, but just like with the custom font code, it can be done at a source level.

**Comment by toolstack** [comment]
Closing as GTK doesn't support user based stylesheets.
