### ISSUE TITLE
File contents erased without warning

### ISSUE THREAD

**Issue by stewlab** [toolstack/Folio#118]
I opened a markdown file externally using this app via the context menu in my file browser, and noticed that the file was automatically erased and written back to disk, with no way to recover.  Strange bug.

**Steps to reproduce:**
- navigate to a populated markdown file in Gnome Files
- right click file > Open With.. > (select Folio)
- notice that the file is now empty after being erased by Folio

I am not sure if Folio supports opening files externally, but it seems that it should at least fail gracefully with a warning or something similar. Additionally, I will take a look at the code to see if I can find the source of the issue.

OS:
Fedora Linux 40 (Silverblue) / Gnome 46

**Comment by toolstack** [comment]
I can't reproduce the issue here (Fedora 40 regular), can you re-confirm the behaviour?

**Comment by toolstack** [comment]
If you do reconfirm, can you run Folio from the command line to see if it generates any message, aka:

```flatpak run com.toolstack.Folio --file Note.md``

**Comment by stewlab** [comment]
This is no longer an issue for me. I reinstalled the the Folio flatpak (w/ a clean config) and cannot reproduce via the context menu or CLI, so this may have been a broken config or something similar. Thanks for looking into it!

**Comment by toolstack** [comment]
Np.
