### ISSUE TITLE
Empty `~` folder is created in `$HOME` when moving note to trash

### ISSUE THREAD

**Issue by fiftydinar** [toolstack/Folio#123]
When clicking "Move to trash" or "Restore to trash", UI changes accordingly, but when I follow the data directory, I see that nothing is happening, due to typo for `~/` directory.

**Comment by fiftydinar** [comment]
I see it's already fixed, closing

**Comment by somepaulo** [comment]
Still happening with Flatpak app

**Comment by fiftydinar** [comment]
> Still happening with Flatpak app

Yeah, it's not in releases yet, but git.

**Comment by toolstack** [comment]
Hoping to get some time later this week to do some bug fixes and a release.
