### ISSUE TITLE
FEAT: add mermaid  for create diagrams and visualizations using text and code

### ISSUE THREAD

**Issue by ssmns** [toolstack/Folio#124]
The Folio is one of the best Markdown editors I have used. However, some packages are missing, such as `mermaid ` for rendering diagrams and `MathJax` for rendering LaTeX equations. I suggest either adding these libraries to Folio or implementing a plugin system to allow users to add custom JavaScript libraries.

**Comment by toolstack** [comment]
Folio isn't javascript based, so these libraries aren't applicable.

There is an extension to the renderer for LaTeX (see #108) but I'm not sure I'll add it.
