### ISSUE TITLE
Feature request: Line spacing

### ISSUE THREAD

**Issue by LukaszH77** [toolstack/Folio#129]
The ability to set line spacing would greatly improve the comfort of working with longer texts. You can see the difference below. 

Fira Code 12pt with 1.5 spacing in ThiefMD:
![obraz](https://github.com/toolstack/Folio/assets/121253127/cf3f5623-65f6-4612-b40b-1fe5a5101222)

Fira Code 12pt in Folio:
![obraz](https://github.com/toolstack/Folio/assets/121253127/94215e78-d240-4c3b-a964-a90e2802e229)

**Comment by toolstack** [comment]
Should be doable, though I'll leave the default as single space.
