### ISSUE TITLE
Markdown Highlight (==) Breaks Detected URL

### ISSUE THREAD

**Issue by SoloRobo** [toolstack/Folio#135]
Using markdown highlight ==example.org== adds the == to the end of the detected url e.g.

==example.org==

becomes

http://example.org==

**Comment by toolstack** [comment]
I don't seem to be able to reproduce this, could you provide an example file where you're see this occur?

**Comment by toolstack** [comment]
PR #147 may resolve this as well.

**Comment by SoloRobo** [comment]
Using flatpak version 24.11

File uploaded (had to use .md extension to make that happen)

[folio-example.md](https://github.com/user-attachments/files/16261538/folio-example.md)

**Comment by toolstack** [comment]
Works fine for me...

![Screenshot from 2024-07-17 16-20-46](https://github.com/user-attachments/assets/e66a5f85-af3a-4e46-b1ce-e85597171c36)

What distro are you using?

**Comment by SoloRobo** [comment]
I'm using Fedora 40, Gnome 46 and its opening in Firefox 128

![image](https://github.com/user-attachments/assets/9f9f94d2-8990-4154-9b99-fcdd968e462f)

It's when ctrl clicking on the markdown highlighted URL the double = (==) are appended as you can see above.

**Comment by toolstack** [comment]
Ok, I understand now and can replicate, will look into it.
