### ISSUE TITLE
Git support & Extensions

### ISSUE THREAD

**Issue by 2bw3** [toolstack/Folio#139]
A built-in feature like [the Git extension for Obsidian](https://github.com/Vinzent03/obsidian-git) could be useful.  Adding a whole extension system could be an overblow, (although it would help expand the application's abilities and be a weight off the maintainer's shoulders) but Git support might be an essential.

As for the primary feature request, it could be something straightforward; periodic committing and pushing (after setting up the remote.)  Although, if an extension system was added, anyone (including myself) could program extensions.

**Comment by toolstack** [comment]
In my opinion Folio's main strength is it's simplify, so extensions and git integration would be antithetical to that.

I don't see this as something that would be added.

**Comment by 2bw3** [comment]
I agree about the extensions but would Git integration be such as well? I am not sure.  Anyways, all power to your elbow.

**Comment by toolstack** [comment]
I would think yes, Folio doesn't much care about the underlying file system, as long as it's there.  Trying to integrate git would be a significant change in how Folio deals with files.
