### ISSUE TITLE
Cannot change where files are saved/stored

### ISSUE THREAD

**Issue by calinadamut** [toolstack/Folio#141]
I'd like to store my files on a shared network folder (to share them also with my other computer from my local network) but I cannot add the shared folder path into Preference/Files/Notes Storage Location

Any solution? Am I missing something?

Thank you
![Screenshot from 2024-07-11 11-03-28](https://github.com/toolstack/Folio/assets/88799030/d709aed0-68b3-480f-bd95-2019b0e177a2)

**Comment by toolstack** [comment]
I'm going to assume you're using the flatpak, in which case it's probably a permissions issue.  By default Folio only has permissions to your local home folder, no where else.

I'd suggest grabbing flatseal and adding your desired locations to the file permissions.

FYI, I won't change the default permissions, as flathub has scary warnings if you give an app too many permissions, even what I've done throws a security warning on the flathub page.

**Comment by toolstack** [comment]
Closing for now as no additional feedback provided.
