### ISSUE TITLE
Unable to open files for editing in gvfs mount points

### ISSUE THREAD

**Issue by eexpress** [toolstack/Folio#143]
Although I can mount "davs://" to nautilus using gvfs. However, folio cannot operate this mount point. It would be more convenient if WebDAV could be set up directly.

**Comment by toolstack** [comment]
When you say that Folio can't operate this mount point, do you mean that it can't see it or that when you use it something fails?

I can use a dav mountpoint without issue using Nextcloud as the backend.

**Comment by eexpress** [comment]
The simplest mount is to create a bookmark in nautilus. I am not manually using the command to mount. (At this moment, the actual mount point is under /var/user/1000/gvfs/.) I can open a single file with marktext or marker, but not folio.

**Comment by toolstack** [comment]
Ok, I've been able to replicate the issue, let me take a look.
