### ISSUE TITLE
Feature Request: Only select the file name (not extension) after toggling rename of the note

### ISSUE THREAD

**Issue by amethylghostling** [toolstack/Folio#144]
... whether it is done through the secondary-click context menu, keyboard shortcut, or double-clicking on the title.

This is the same rename selection behavior as in all good file managers. It makes sense to have it because most of the time you only want to change the title of the note, not the extension. It's still easy enough to change the extension after toggling rename, you just have to double-click on it to select it and then replace it with whatever extension you want.

**Comment by toolstack** [comment]
Makes sense to me.

**Comment by toolstack** [comment]
Doesn't look like it's possible to only select a part of the text in gtk, but I can select no text, so I'll do that instead.

**Comment by amethylghostling** [comment]
> Doesn't look like it's possible to only select a part of the text in gtk, but I can select no text, so I'll do that instead.

I mean it happens in nautilus so I am pretty sure it can happen in gtk.

https://github.com/user-attachments/assets/8591632f-e0db-4ebd-8816-3ee32d893875

**Comment by toolstack** [comment]
There are several different parts of gtk, the widget that is being used for the rename function in Folio doesn't seem to have a selection control.  More than likely it's a different widget in Nautilus that does.

**Comment by amethylghostling** [comment]
> There are several different parts of gtk, the widget that is being used for the rename function in Folio doesn't seem to have a selection control. More than likely it's a different widget in Nautilus that does.

Is it feasible for you to switch the widget to the one that Nautilus uses?

**Comment by toolstack** [comment]
It would require a major rewrite of the list code to make the change.

**Comment by amethylghostling** [comment]
> Doesn't look like it's possible to only select a part of the text in gtk, but I can select no text, so I'll do that instead.

You could hide the file extension in the note titles like in Paper and then have the whole name be selected instead if changing file extensions isn't a feature that Folio needs.

**Comment by toolstack** [comment]
I removed that function from Folio while fixing another bug associated with it, Folio does allow for MD and text formats, based on extension, so it's required.

**Comment by amethystgosling** [comment]
> I removed that function from Folio while fixing another bug associated with it, Folio does allow for MD and text formats, based on extension, so it's required.

Which function are you talking about?

**Comment by amethystgosling** [comment]
> I removed that function from Folio while fixing another bug associated with it, Folio does allow for MD and text formats, based on extension, so it's required.

What does removing this function do for this issue?

**Comment by toolstack** [comment]
It was how it was removing extensions, as it just stripped anything from the first period to the end of the filename off and then displayed it in the edit field.  This meant that you couldn't have a note name with a period in it.
