### ISSUE TITLE
Feature request: close to tray

### ISSUE THREAD

**Issue by toxpal** [toolstack/Folio#153]
Just installed this on Manjaro KDE as a possible replacement for QOwnNotes (which is great, but has too many features for basic notes) and I miss an option to close app to tray.

Since I read/modify my notes very often during my job (every few hours usually, because they contain lots of "to-do" stuff), I prefer to always have app accessible. However, since it's only needed for a minute or two every few hours, it would be great to close app top tray (so it doesn't waste desktop space, but is still one click away).

Anyone else missing this feature?

**Comment by toolstack** [comment]
Gnome has deprecated the tray (not that I agree with it, but it's just the case) so that doesn't seem like something that would be added 🤷

**Comment by toxpal** [comment]
Oh, that's sad to hear... I use this app on KDE, but I got the idea :) Thanks for the explanation.

**Comment by toolstack** [comment]
Np.
