### ISSUE TITLE
Making a general markdown editor

### ISSUE THREAD

**Issue by machitgarha** [toolstack/Folio#154]
Folio is great. It has by far one of the best markdown-editing tools. It is simple and fast, I can customize its font, and one thing that makes it much more special for me: it supports RTL languages perfectly.

Is there any chance of having an app with markdown editing feature of this app? I don't know if making a separate app makes sense (like splitting the things needed for the new app as an independent library or something), but I think making this app a general markdown editor breaks existing users, so it might not be a good decision.

What's your comment on this?

**Comment by toolstack** [comment]
You can already edit markdown documents with Folio in a single window (aka without the notebooks) and outside of the data directory.

In your file explorer just right click the markdown file you want to edit, select "open with", then select Folio.  You of course can set it to the default editor as well if you prefer.  From the command line, just use the -f/--file option to edit a note.
