### ISSUE TITLE
Feature Request: Add a new note addition dialog

### ISSUE THREAD

**Issue by amethystgosling** [toolstack/Folio#161]
The dialog takes a name and an extension (through a dropdown). The extension could then be changed through an option inside the secondary-click menu of the note called "Change File Extension" after it has been added. So, the note name with the extension that is shown while renaming isn't required to have the extension so it can be removed, and therefore the name can be selected in full automatically after it is set to rename without causing complications, fixing #144 (the right way) while taking the needs of the user in #120 into account, while also allowing changes to file extensions of notes easier for average users and also making the file extensions supported by Folio discoverable from inside the app.

**Comment by toolstack** [comment]
A drop down wouldn't work, as it would have to have every possible extension in it, and it still would require significant 
 work on the list code to implement anyway.

Likewise an entire new dialog box seems like a bad user interface choice for a rename.

I'm going to close this as a wont-fix, but am still open to other suggestions or ideas on how to improve the rename code.
