### ISSUE TITLE
Sorting order for notes with numbers

### ISSUE THREAD

**Issue by qumuq-til** [toolstack/Folio#163]
I keep my notes numbered so they're supposed to go be listed like this:

- Note 1
- Note 2
- Note 3
- ...
- Note 10
- Note 11
- Note 12

But when asked to sort notes in alphabetical order Folio presents the following list:

- Note 1
- Note 10
- Note 11
- Note 12
- Note 2
- Note 3

Folio should respect the numbering so that "Note 1" is followed by "Note 2" instead of relying on purely numerical/alphabetical sorting.

Same thing applies to notebook list.

**Comment by toolstack** [comment]
This is as intended, alpha sorting will always sort this way as it's not seeing the numbers, only the characters that make them up and a shorter string will always be sorted first.

An easy workaround is to label your notes with zero padding, so:

```
Note 01
Note 02
Note 03
...
Note 10
Note 11
Note 12
```

This will sort them in the "right" order.

I could see adding a "Alpha/Numeric" sort option as well, so I'll keep this issue open.
