### ISSUE TITLE
Some lines have line indents while others do not

### ISSUE THREAD

**Issue by qumuq-til** [toolstack/Folio#164]
Consider the following snippet

```
numero uno
12411116 3.0.9

192218181 ttc
3758136b
```

When copypasted into a new note in Folio the snippet looks like this:

```
numero uno
  12411116 3.0.9

  192218181 ttc
3758136b
```

Whatever the cause, all lines should start with a zero indent, at least there should be an option for that. I don't use Folio for writing long texts, mostly just to keep some data, so those indents are a nuisance.

**Comment by toolstack** [comment]
Well that's very strange, the number has to have a space after it to trigger this behaviour as well.

**Comment by machitgarha** [comment]
This might be because of the text being mistakenly considered as an ordered list, due to the incorrect regex in the code.

**Comment by toolstack** [comment]
Agreed that the ordered lists formatting is likely the root cause.
