### ISSUE TITLE
Shell search provider result doesn't activate

### ISSUE THREAD

**Issue by cheywood** [toolstack/Folio#176]
Using the v24.11 Flatpak Folio will show results searching from GNOME Shell but clicking on one of them doesn't result in any action.

Reproduce:
1. Search in the shell
2. See Folio results listed
3. Click on one of the results
4. Observe Folio not opening

Tested with Folio closed and already open, either way nothing seems to happen. Testing with GNOME v46.

**Comment by toolstack** [comment]
Confirmed, looks like there's a segfault when opening a note from the command line.
