### ISSUE TITLE
Pressing Ctrl and scrolling at the same time

### ISSUE THREAD

**Issue by sirandreww** [toolstack/Folio#182]
[Screencast from 2024-10-05 11-41-29.webm](https://github.com/user-attachments/assets/1d17df86-5411-4375-8e64-8a4c1050b5b6)

H2 headers change but the code segment does not change.

**Comment by toolstack** [comment]
Looks like it has something to do with the MD formatting of code and some other block types.

**Comment by toolstack** [comment]
Ok, I've tracked down the issue, it's with the monospace code not updating the font size.  It will take a bit to fix due to how the code works, but I should get it in the next release.
