### ISSUE TITLE
AppImage of version 24.12 doesn't launch

### ISSUE THREAD

**Issue by Bochrm** [toolstack/Folio#190]
Greetings. The AppImage (Folio-24.12-x86_64.AppImage) fails to run, with the following error in the terminal:

`(com.toolstack.Folio:38276): GLib-GIO-ERROR **: 17:27:12.604: Settings schema 'com.toolstack.Folio.Theme' is not installed`

System info:
Operating System: Fedora Linux 40
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.3-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland

Identical error on clean Fedora 40 GNOME and Ubuntu 24.04 VM's, besides another line:

```
(com.toolstack.Folio:3964): GLib-GIO-ERROR **: 17:44:45.543: Settings schema 'com.toolstack.Folio.Theme' is not installed
Trace/breakpoint trap (core dumped)
```

**Comment by toolstack** [comment]
Yeah, I've been trying to track down why the error comes up, but I'm not an AppImage expert ;)

Might be able to include the complied schema in the appimage file itself though.

**Comment by toolstack** [comment]
Also, related to #136

**Comment by toolstack** [comment]
Nope, just adding the compiled schema to the appimage doesn't work.

**Comment by toolstack** [comment]
Ok, I've found a fix, it's kinda manual for the build, but afterwards the appimage seems to work fine.

Will post an update appimage shortly.
