### ISSUE TITLE
notebooks and note columns too small

### ISSUE THREAD

**Issue by PHHENS** [toolstack/Folio#192]
Dear Developer,
Cannot read entirely notebook and notes names, because those 
two columns are not wide enough...
Thanks.

**Comment by toolstack** [comment]
Will take a look, probably related to the migration to the newer gtk widgets.

**Comment by toolstack** [comment]
@turtlegarden any thoughts on this one?

**Comment by turtlegarden** [comment]
The columns _seem_ to work fine on my machine, but I have shorter notebook names. I can see if the widgets can be made to expand more, but they'll be too small anyway based on how libadwaita handles the side view.

**Comment by toolstack** [comment]
I just compared against how it was previously handled, which is the same, so not anything connected with the widget updates.

I think this will be something to think about, but at the moment it's expected behaviour.

Changing it to a feature request.

**Comment by PHHENS** [comment]
Resolved in 24.13 : need to activate appropriate preferences
Thanks
