### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by machitgarha** [toolstack/Folio#197]
Thank you for maintaining this project. It is great, and I appreciate it.

My question is, how different releases are published? I think features reach users in a timely manner, and making releases smaller would be great. What is your opinion?

**Comment by toolstack** [comment]
Releases are published when they're ready and I have time to do them 😁

The last release was a pretty big one and kind of an outlier in that regard.  Previous releases were smaller and more frequent.

**Comment by machitgarha** [comment]
Great!
