### ISSUE TITLE
Preventing from losing work when the application crashes 

### ISSUE THREAD

**Issue by machitgarha** [toolstack/Folio#199]
I've had a couple of crashes last week, and because I was not used to press Ctrl+s regularly, some of my work was lost.

Now, I think there should be a way to prevent this. There are two main features coming to my mind (the former is the easier one): Auto-saving on focus lose feature; or regularly saving the work in a cache somewhere, and recovering the previous state when the application crashes.

**Comment by machitgarha** [comment]
Ah. Sorry. Thank you.

But I have already enabled it, and after hours of works it seems it didn't work correctly. Why is this the case?

**Comment by toolstack** [comment]
The auto save code writes out the file every 30 seconds, so it should catch most cases.

When you say you had a crash, was it the app or the os?

The only thing that comes to mind here is that if it was the OS then perhaps your disk cache wasn't written to the ssd/disk.

**Comment by machitgarha** [comment]
It was the app.

I tested the app and waited for 30 seconds, and it didn't auto-save.

**Comment by toolstack** [comment]
I can reproduce so I'll take a look and see what's going on.
