### ISSUE TITLE
New notebook: No padding between top icon and titlebar

### ISSUE THREAD

**Issue by vanillajonathan** [toolstack/Folio#208]
When I create a new notebook there is no padding between the icon and the titlebar.

**Comment by toolstack** [comment]
Can you provide a screenshot?

**Comment by vanillajonathan** [comment]
![image](https://github.com/user-attachments/assets/2fd9f256-a828-449b-9a1a-ded58ac5aa2d)

**Comment by toolstack** [comment]
Thanks.
