### ISSUE TITLE
Scroll Bar for Notes

### ISSUE THREAD

**Issue by BruceWayne-Linux** [toolstack/Folio#21]
Hey,
There does not seem to be a scroll bar for notes. The arrow keys seem to work to move around notes.
A scroll bar would be nice too.
[Screencast from 2024-03-05 15-35-30.webm](https://github.com/toolstack/Folio/assets/87817029/d812859c-ec00-4e9c-a06b-304f879dfc0b)

**Comment by toolstack** [comment]
That is definitely a problem.

**Comment by BruceWayne-Linux** [comment]
That was fast man. 

BTW, Thanks for reviving the project.

**Comment by toolstack** [comment]
Np.
