### ISSUE TITLE
Folio crashes when trying to find a renamed folder

### ISSUE THREAD

**Issue by IndiumInLCD** [toolstack/Folio#23]
Folio crashes when renaming through an external tool (i.e. , a file manager).
Steps to reproduce : 
- Open Folio
- Choose a folder to be on (doesn't matter which one)
- Rename through an external tool a folder (doesn't matter which one)
- Click on the renamed folder and click back (also works if you are already on the renamed folder).
- Folio crashes and produces the following output : 

`(com.toolstack.Folio:2): GtkSourceView-WARNING **: 19:49:15.650: in file /app/share/gtksourceview-5/language-specs/markdownpp.lang: style 'def:text' not defined

(com.toolstack.Folio:2): Gtk-WARNING **: 19:49:15.982: GtkBox 0x5f62c4380500 (box) reported min width -3, but sizes must be >= 0

(com.toolstack.Folio:2): Gtk-WARNING **: 19:49:18.919: GtkBox 0x5f62c4768940 (box) reported min width -3, but sizes must be >= 0

** (com.toolstack.Folio:2): ERROR **: 19:49:35.019: file_utils.vala:24: Erreur lors de l’ouverture du fichier « /home/basilek/Documents/Markdown/Oral stage BUT-S2/Première partie.md » : No such file or directory`

**Comment by toolstack** [comment]
Folio expects you **_not_** to be messing with the underlying documents while it's running.

I've created a fix that will recreate the directory as needed which will avoid the crash, but may lead to duplicate notes 🤷
