### ISSUE TITLE
Feature request: "Preview" mode

### ISSUE THREAD

**Issue by kevinlearnscoding** [toolstack/Folio#235]
Feature request: editing mode and preview mode. 

I've never been able to get Folio to work quite right, I know it should be what you see is what you get, but as I type sometimes it converts to the final form, and sometimes it just shows me the plain text and keeps on going - even when using the "insert" buttons down at the bottom of the window. 

I'd like to have the ability to turn on a "preview" of the MD while "editing" is the default view.

**Comment by toolstack** [comment]
That would go against the fundamental design of Folio, there are lots of markdown editors that use that kind of layout for edit/preview already.  The WYSIWYG model that Folio uses is at the heart of the app, so this won't change.
