### ISSUE TITLE
Support for Nextcloud Notes

### ISSUE THREAD

**Issue by lightonflux** [toolstack/Folio#28]
Support for Nextcloud Notes would be great. Is this within the scope of this project, or do you plan to keep Folio a local only Markdown Notes editor?

**Why?**

* There are already many Nextcloud users in the Linux community
* It would enable you to write notes when on your non Linux phone
* It would enable you to sync your notes on your Linux phone and Desktop
* Users can write notes on the go, reducing the risk to forget ideas (or what ever they want to note down) 

**How?** 
Nextcloud Notes has a simple API, which is documented [here](https://github.com/nextcloud/notes/blob/main/docs/api/v1.md).

There is already another Adwaita App that uses the Nextcloud Notes API. But its markdown capabilities are a bit limited. 

https://gitlab.gnome.org/cheywood/iotas/-/tree/main/iotas

**Comment by toolstack** [comment]
I use Folio with Nextcloud Notes all the time, just point the Folio storage location in preferences to your sync'd Nextcloud folder and away you go.  The Nextcloud desktop client will automatically sync changes to your server and then your mobile clients can access them through the API.

I don't see adding Nextcloud Notes API support as likely.  Too much of the underlying code is file system based, it would take a lot of work to add it.

**Comment by kuiperzone** [comment]
>I use Folio with Nextcloud Notes all the time

Not directly Folio related, but do you mind if I ask who/what you are using for your NextCloud host?

I have some traditional webhost space and installed NextCloud on it, but never managed to get either Gnome or a mobile device to connect to it. So wondering if there's something out there which just works, even if paid for?

**Comment by toolstack** [comment]
I host my own server, so I can't help with a webhost, but the nextcloud site does have several [listed](https://nextcloud.com/athome/) that should "just work".

**Comment by lightonflux** [comment]
With Paper there were some issues with Nextcloud. E.g. when you edited a note on your phone while Paper was open, you had to restart Paper to see / load the changed note. 

Is this still an issue with Folio? How do you use it? @toolstack 

Thanks for your clarification.

**Comment by toolstack** [comment]
Same with Folio at the moment, neither tracks changes on the filesystem.

Most of my note editing is done on desktop, so I mostly just read notes on mobile.

**Comment by toolstack** [comment]
Likewise, #53 helps with Nextcloud compatibility as you can "unhide" the trash so you get a nicer looking non-Folio experience (instead of having a folder with a period at the beginning of it).

**Comment by toolstack** [comment]
Step two has been committed with #57, Folio will now watch for changes in the currently loaded note and auto reload the note if there has been no changes in the note within Folio, and prompt for what to do (reload/overwrite) if the note has changed in Folio.

Likewise Folio now checks to see if the note has changed on disk when saving it, and if it finds a newer timestamp on disk prompts for what to do (reload/overwrite/cancel) before committing the note to disk again.  This is an unlikely event now that the note is monitored for changes but could happen if the file system isn't very timely in reporting changes, doesn't support the monitoring of changes, or the user is unlucky and basically saves a note just as the change is happening on disk.

At some point I'll add another monitor to watch for additions of notes/notebooks, but I'll create a separate issue for that.

As such, I'll mark this issue as resolved, as this is as far as I'm willing to go with it at the moment.
