### ISSUE TITLE
Add option to disable trashcan

### ISSUE THREAD

**Issue by toolstack** [toolstack/Folio#29]
The trashcan is a nice safety net, but some users might not want it, so create an option to disable it directly delete notes when told to.

**Comment by frandavid100** [comment]
Maybe it could integrate into Gnome's trashcan. e.g. show .md files that are there and send deleted .md files there?

**Comment by toolstack** [comment]
I've been thinking about this and flip flopping between closing it as a won't fix and trying to do something with the system recycle bin.

I'm pretty sure that just a "permanent delete" option with no recovery of any kind isn't something I want to do now.

My current ideas are:
1. Allow you to define where the trash can lives (put it in the system recycle bin or anywhere else you like)
2. Allow you to unhide the trash can
3. Maybe let you rename the trash can folder as well.

**Comment by toolstack** [comment]
I've merged a patch for 2, I think I'll implement 1 as well, but will not allow 3, then I'll close this issue.

**Comment by toolstack** [comment]
Second patch merged, closing issue.
