### ISSUE TITLE
Feature Request: Click (or copy) link from notes

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#3]
Adding a link using `[]()` is great. However, it is not (seemingly) possible simply click on the link and have in open a browser. Moving the cursor over the link leaves it at the insert cursor, and pressing CTRL does nothing.

In fact, using `[]()` makes it harder to get the link into a browser because you have to manually select the text, and when you do so, that shifts the link into edit mode.

Is it possible that, when you hold down CTRL, moving the cursor over a link shows the point cursor and clicking opens a browser?

If not possible, is it possible to simply put a copy button next the link when not editing it?

Thank you

PS. Folio/Paper is both simple and brilliant.

**Comment by toolstack** [comment]
Looks like it should be doable and makes sense.  I'll look into it when I get some time.

**Comment by kuiperzone** [comment]
My only thought was that there might be an issue opening a browser from a flatpak app, hence the copy alternative. Thank you!

**Comment by toolstack** [comment]
Shouldn't be an issue, I have several flatpak apps that open links in external web browsers.
