### ISSUE TITLE
Create new notes and link to them automatically 

### ISSUE THREAD

**Issue by frandavid100** [toolstack/Folio#39]
I used to use a note-taking app called Tomboy, which had this really, really useful feature:

While you were inside a note, you could select text (e.g. select the words "shopping list" and click a specific button; then, a new note called "shopping list" would be created; and every time you wrote the words "shopping list" in any other note, they would link to that note.

Again: it was extremely useful.

Is there any chance that Folio could have this feature?

**Comment by toolstack** [comment]
There was another request for linking between notes and I think it is a reasonable idea, though not something that will happen quickly as it will require a bit of work.

Auto highlighting note titles seems less likely as a feature, though perhaps checking when inserting a md link to see if it matches a title might be doable.
