### ISSUE TITLE
Not possible to change the icon of a notebook

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#4]
It does not seem possible to update the icon in a notebook -- Apply stays grayed out.

See screenshot.

![image](https://github.com/toolstack/Folio/assets/17156238/3beaa8f9-8b57-4ed1-842f-638df48f2c93)

**Comment by toolstack** [comment]
A bug in the previous fix for #2, as that disallowed duplicate name but doesn't check to see if we're creating or editing.  Should be an easy fix.

**Comment by toolstack** [comment]
Fix committed to main.
