### ISSUE TITLE
Move a note to a different notebook 

### ISSUE THREAD

**Issue by frandavid100** [toolstack/Folio#40]
Could there be an option to take an existing note and adding it to a different notebook? Thanks!

**Comment by frandavid100** [comment]
Oh,

**Comment by frandavid100** [comment]
Sorry, I had not noticed it can already do exactly what I asked.

**Comment by toolstack** [comment]
Np, there are two methods to moving notes, either through the right click menu of a note or just by dragging and dropping a note onto a new notebook.
