### ISSUE TITLE
Implement autosave

### ISSUE THREAD

**Issue by frandavid100** [toolstack/Folio#42]
What the title says. It would be very useful to have notes saved automatically after a change happens.

**Comment by toolstack** [comment]
They do autosave when you navigate to a new note, but agree that a scheduled save after a set time probably makes sense.

**Comment by frandavid100** [comment]
Just curious, do they have if you close the app without switching to a new note?

**Comment by toolstack** [comment]
Yes.

**Comment by frandavid100** [comment]
Then I guess this change would only be important because of the psychological factor of knowing your changes are saved.

**Comment by frandavid100** [comment]
Hi! It seems that, when the note is autosaved, it scrolls back to the top. Should I open a new issue about that?

**Comment by toolstack** [comment]
@frandavid100 Yes please do.

**Comment by amethystgosling** [comment]
> Just curious, do they save if you close the app without switching to a new note?



> Yes.

Does this rely on the Run In Background setting?

**Comment by toolstack** [comment]
> > Just curious, do they save if you close the app without switching to a new note?
> 
> > Yes.
> 
> Does this rely on the flatpak "Run In Background" setting?

No, the app is running in the foreground (aka has a GUI thread running) until it closes so no background permission is needed.

**Comment by amethystgosling** [comment]
> > > Just curious, do they save if you close the app without switching to a new note?
> > 
> > 
> > > Yes.
> > 
> > 
> > Does this rely on the flatpak "Run In Background" setting?
> 
> No, the app is running in the foreground (aka has a GUI thread running) until it closes so no background permission is needed.

Still, though I think the autosave should happen with every change to prevent loss on Desktop PCs which can happen if there was some unsaved text data immediately before a power outage.
