### ISSUE TITLE
Appdata screenshot papercuts

### ISSUE THREAD

**Issue by bertob** [toolstack/Folio#48]
There are a few minor issues with the current appdata screenshots:

- Window is not focused (see unfocused headerbar items)
- Window size larger than 1000x700px (I'm pretty sure, though didn't check)
- Non-standard window controls (should be close-only)

Flathub guidelines: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/

**Comment by toolstack** [comment]
Thanks, I've redone them, will be included in the next release later this week.
