### ISSUE TITLE
Broken 24.07

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#64]
Now doesn't show anything.

See Folio vs Paper.

Sorry.

![image](https://github.com/toolstack/Folio/assets/17156238/d4a217d2-0b8e-4000-9336-87dc9713d7b3)

**Comment by toolstack** [comment]
That seems to be a bug in the new font size code, go in to preferences and set your font/size, it looks like it's defaulting to 0 for some reason.

**Comment by toolstack** [comment]
24.08 is released and should resolve.
