### ISSUE TITLE
Inform translators before new releases

### ISSUE THREAD

**Issue by yakushabb** [toolstack/Folio#66]
Good to see the Paper project having a new life under the name of Folio.

Please inform the translators about the fork and your project before new releases. They would probably be happy to update the translations.

Thanks.

**Comment by toolstack** [comment]
It is next on my list of things to do 😁

**Comment by toolstack** [comment]
Updated readme to include translator notification as well as sent an e-mail to the known translators of Paper to see if they want to support Folio.
