### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by soumyaDghosh** [toolstack/Folio#8]
Hi, I previously created a snap for the `paper`, and have a snap for this app also. Would you like to have it as official?

**Comment by toolstack** [comment]
Thanks, I was debating if I was going to make a Snap/AppImage for Folio, if you're going to publish it anyway I might as well make it official 😁

**Comment by soumyaDghosh** [comment]
Thanks.. I'll create a PR with all the necessary files to upload to the store then. Until then, please create an account in https://snapcraft.io/snaps and register the name `folio`

**Comment by toolstack** [comment]
FYI I built the snap package and submitted it today, it's pending manual review for:

>human review required due to 'deny-connection' constraint (interface attributes) declaration-snap-v2_slots_connection (folio, dbus)

**Comment by soumyaDghosh** [comment]
Yeah, it'll be reviewed and checked before allowing to use the dbus name. It'll be available soon, within next 1-2 days.

**Comment by toolstack** [comment]
Now published, thanks for the PR.
