### ISSUE TITLE
Alpha sort for notebooks is wrong way round 24.09

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#83]
Setting Ascending for Notebooks reverse sorts it.

![image](https://github.com/toolstack/Folio/assets/17156238/4fbf599e-4c09-4c3d-9018-75c46a0fa375)

May I suggest you consider naming these "Alphabetical" and "Reverse Alphabetical"? I have to think which way is "Ascending". In any case, the Notebooks and Notes sort the opposite way to each other, as above.

Moreover, I cannot actually think of a use case for "Reverse Alpha" as a setting?

**Comment by toolstack** [comment]
I named them as I did for consistency between alpha and time sorting, I think the naming is fine.

I've fixed the reversed sort order for the next release.
