### ISSUE TITLE
image syntax from the cheatsheet doesn't work

### ISSUE THREAD

**Issue by 2-www** [toolstack/Folio#91]
in the built-in cheat sheet you can see this:

>`![Image alt text](https://imageurl.io)`

but it doesn't actually work in notes, it's just a "!" and a link

**Comment by toolstack** [comment]
Yeah, I noticed myself that a few days ago, images are probably the next feature I'll add.  I'm doing a release tomorrow and have pulled it out of the cheet sheet for now.

I'll add it back in when images are implemented as part of #27.
