### ISSUE TITLE
URL detection is too aggressive

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#98]
From what I can see, Folio auto detects a link in the text if merely contains a `.` with no whitespace. As a result, it also characterises simple file names and namespaces as links and my notes are littered with false positive "links".

See screenie.

May I suggest for purposes of auto-link detection, a text fragment must contain (but not start or end with) both:

`://`, `.`

where the first occurrence of `.` must be after the `://` the scheme separator.

Or as well:  a fragment may start with `www.` instead of containing `::/`, though few use www any more.

This obviously shouldn't apply to links explicitly designated with `()[]`.

![image](https://github.com/toolstack/Folio/assets/17156238/a84be34a-be20-41d9-b481-9694168e6276)

**Comment by kuiperzone** [comment]
Hey thanks for the reply!

While I don't want to suggest an option for every problem...

Perhaps there could be an option for auto-detect links with 3 states:

1. Disabled
2. Cautious/Normal (using ://)
3. Aggressive/Verbose (as current)

?

**Comment by toolstack** [comment]
Perhaps, but I really want to rewrite the regex processor anyway at some point so don't want to put a whole lot of effort into playing whack a mole with the existing one.

**Comment by kuiperzone** [comment]
If we cannot have a robust URL detector, can we at least disable the auto URL detection. I don't actually see it as useful, but understand others might.

I guess this is content specific, but if you are keeping IT related notes than more than half of "URLs" will be false positives.

It falsely detects the following as URLs:

ISO times
filenames
version numbers
namespaces
Anything with a period in it

**Comment by toolstack** [comment]
I was thinking of adding a disable url detection option, so I don't see that being an issue.

Unfortunately url detection is a messy business in free form text, so it's never going to be perfect.

I might do a three way selector; aggressive, strict, disable.

Strict would require a proper protocol part to exist (aka https://, etc.) before it was identified as a url.

**Comment by kuiperzone** [comment]
Good stuff!

Aggressive and strict? That doesn't sound fun. I'll be selecting disabled. :)
